// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID        string
	PesNumber string
	Password  string
	FirstName string
	LastName  string
	Email     string
	Role      string
	Cluster   sql.NullString
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	ManagerID sql.NullString
}
