// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, pes_number, password, first_name, last_name, email, role, cluster, is_active, created_at, updated_at, manager_id FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagerID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, pes_number, password, first_name, last_name, email, role, cluster, is_active, created_at, updated_at, manager_id FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PesNumber,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.Cluster,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
