// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"go-server/internal/models"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    id, title, description, author_id, cover_image_uri, status,
    category, estimated_durations, learning_outcomes, is_strict_sequencing,
    version, published_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, description, author_id, cover_image_uri, status, category, estimated_durations, learning_outcomes, is_strict_sequencing, version, published_at, created_at, updated_at
`

type CreateCourseParams struct {
	ID                 uuid.UUID               `json:"id"`
	Title              string                  `json:"title"`
	Description        sql.NullString          `json:"description"`
	AuthorID           uuid.NullUUID           `json:"author_id"`
	CoverImageUri      sql.NullString          `json:"cover_image_uri"`
	Status             models.CourseStatus     `json:"status"`
	Category           models.TrainingCategory `json:"category"`
	EstimatedDurations sql.NullInt64           `json:"estimated_durations"`
	LearningOutcomes   string                  `json:"learning_outcomes"`
	IsStrictSequencing bool                    `json:"is_strict_sequencing"`
	Version            int64                   `json:"version"`
	PublishedAt        sql.NullTime            `json:"published_at"`
}

// COURSE
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.CoverImageUri,
		arg.Status,
		arg.Category,
		arg.EstimatedDurations,
		arg.LearningOutcomes,
		arg.IsStrictSequencing,
		arg.Version,
		arg.PublishedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CoverImageUri,
		&i.Status,
		&i.Category,
		&i.EstimatedDurations,
		&i.LearningOutcomes,
		&i.IsStrictSequencing,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNomination = `-- name: CreateNomination :one
INSERT INTO nominations (
    id, status, user_id, training_id, nominated_by_id,
    hr_completion_status, prof_fees, venue_cost, other_cost,
    non_tems_travel, non_tems_accommodation, total_cost
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
RETURNING id, status, user_id, training_id, nominated_by_id, hr_completion_status, prof_fees, venue_cost, other_cost, non_tems_travel, non_tems_accommodation, total_cost, created_at, updated_at
`

type CreateNominationParams struct {
	ID                   uuid.UUID               `json:"id"`
	Status               models.NominationStatus `json:"status"`
	UserID               uuid.UUID               `json:"user_id"`
	TrainingID           uuid.UUID               `json:"training_id"`
	NominatedByID        uuid.UUID               `json:"nominated_by_id"`
	HrCompletionStatus   sql.NullString          `json:"hr_completion_status"`
	ProfFees             sql.NullFloat64         `json:"prof_fees"`
	VenueCost            sql.NullFloat64         `json:"venue_cost"`
	OtherCost            sql.NullFloat64         `json:"other_cost"`
	NonTemsTravel        sql.NullFloat64         `json:"non_tems_travel"`
	NonTemsAccommodation sql.NullFloat64         `json:"non_tems_accommodation"`
	TotalCost            sql.NullFloat64         `json:"total_cost"`
}

// NOMINATIONS
func (q *Queries) CreateNomination(ctx context.Context, arg CreateNominationParams) (Nomination, error) {
	row := q.db.QueryRowContext(ctx, createNomination,
		arg.ID,
		arg.Status,
		arg.UserID,
		arg.TrainingID,
		arg.NominatedByID,
		arg.HrCompletionStatus,
		arg.ProfFees,
		arg.VenueCost,
		arg.OtherCost,
		arg.NonTemsTravel,
		arg.NonTemsAccommodation,
		arg.TotalCost,
	)
	var i Nomination
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserID,
		&i.TrainingID,
		&i.NominatedByID,
		&i.HrCompletionStatus,
		&i.ProfFees,
		&i.VenueCost,
		&i.OtherCost,
		&i.NonTemsTravel,
		&i.NonTemsAccommodation,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (
    id, title, description, category, start_date, end_date,
    location, virtual_link, pre_read_uri, created_by_id,
    deadline_days, hr_program_id, mapped_category, mode_of_delivery,
    instructor_name, institute_partner_name, process_owner_name,
    process_owner_email, duration_manhours, training_mandays,
    facility_id
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?
)
RETURNING id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at
`

type CreateTrainingParams struct {
	ID                   uuid.UUID               `json:"id"`
	Title                string                  `json:"title"`
	Description          sql.NullString          `json:"description"`
	Category             models.TrainingCategory `json:"category"`
	StartDate            time.Time               `json:"start_date"`
	EndDate              time.Time               `json:"end_date"`
	Location             sql.NullString          `json:"location"`
	VirtualLink          sql.NullString          `json:"virtual_link"`
	PreReadUri           sql.NullString          `json:"pre_read_uri"`
	CreatedByID          uuid.UUID               `json:"created_by_id"`
	DeadlineDays         int64                   `json:"deadline_days"`
	HrProgramID          uuid.UUID               `json:"hr_program_id"`
	MappedCategory       string                  `json:"mapped_category"`
	ModeOfDelivery       models.DeliveryMode     `json:"mode_of_delivery"`
	InstructorName       string                  `json:"instructor_name"`
	InstitutePartnerName sql.NullString          `json:"institute_partner_name"`
	ProcessOwnerName     sql.NullString          `json:"process_owner_name"`
	ProcessOwnerEmail    sql.NullString          `json:"process_owner_email"`
	DurationManhours     sql.NullFloat64         `json:"duration_manhours"`
	TrainingMandays      sql.NullFloat64         `json:"training_mandays"`
	FacilityID           uuid.UUID               `json:"facility_id"`
}

// TRAININGS
func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, createTraining,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.VirtualLink,
		arg.PreReadUri,
		arg.CreatedByID,
		arg.DeadlineDays,
		arg.HrProgramID,
		arg.MappedCategory,
		arg.ModeOfDelivery,
		arg.InstructorName,
		arg.InstitutePartnerName,
		arg.ProcessOwnerName,
		arg.ProcessOwnerEmail,
		arg.DurationManhours,
		arg.TrainingMandays,
		arg.FacilityID,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.VirtualLink,
		&i.PreReadUri,
		&i.CreatedByID,
		&i.DeadlineDays,
		&i.HrProgramID,
		&i.MappedCategory,
		&i.ModeOfDelivery,
		&i.InstructorName,
		&i.InstitutePartnerName,
		&i.ProcessOwnerName,
		&i.ProcessOwnerEmail,
		&i.DurationManhours,
		&i.TrainingMandays,
		&i.FacilityID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, pes_number, password, first_name, last_name,
    email, role, cluster, title, gender, band, grade,
    ic, sbg, bu, segment, department, base_location,
    is_id, ns_id, dh_id
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?
)
RETURNING id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
`

type CreateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	PesNumber    string         `json:"pes_number"`
	Password     string         `json:"password"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Role         models.Role    `json:"role"`
	Cluster      sql.NullString `json:"cluster"`
	Title        string         `json:"title"`
	Gender       string         `json:"gender"`
	Band         string         `json:"band"`
	Grade        string         `json:"grade"`
	Ic           string         `json:"ic"`
	Sbg          string         `json:"sbg"`
	Bu           string         `json:"bu"`
	Segment      string         `json:"segment"`
	Department   string         `json:"department"`
	BaseLocation string         `json:"base_location"`
	IsID         uuid.NullUUID  `json:"is_id"`
	NsID         uuid.NullUUID  `json:"ns_id"`
	DhID         uuid.NullUUID  `json:"dh_id"`
}

// USERS
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.PesNumber,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
		arg.Cluster,
		arg.Title,
		arg.Gender,
		arg.Band,
		arg.Grade,
		arg.Ic,
		arg.Sbg,
		arg.Bu,
		arg.Segment,
		arg.Department,
		arg.BaseLocation,
		arg.IsID,
		arg.NsID,
		arg.DhID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const getCourseWithAuthor = `-- name: GetCourseWithAuthor :one
SELECT
    c.id, c.title, c.description, c.author_id, c.cover_image_uri, c.status, c.category, c.estimated_durations, c.learning_outcomes, c.is_strict_sequencing, c.version, c.published_at, c.created_at, c.updated_at,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name
FROM courses c
JOIN users u ON c.author_id = u.id
WHERE c.id = ?
LIMIT 1
`

type GetCourseWithAuthorRow struct {
	ID                 uuid.UUID               `json:"id"`
	Title              string                  `json:"title"`
	Description        sql.NullString          `json:"description"`
	AuthorID           uuid.NullUUID           `json:"author_id"`
	CoverImageUri      sql.NullString          `json:"cover_image_uri"`
	Status             models.CourseStatus     `json:"status"`
	Category           models.TrainingCategory `json:"category"`
	EstimatedDurations sql.NullInt64           `json:"estimated_durations"`
	LearningOutcomes   string                  `json:"learning_outcomes"`
	IsStrictSequencing bool                    `json:"is_strict_sequencing"`
	Version            int64                   `json:"version"`
	PublishedAt        sql.NullTime            `json:"published_at"`
	CreatedAt          time.Time               `json:"created_at"`
	UpdatedAt          time.Time               `json:"updated_at"`
	AuthorFirstName    string                  `json:"author_first_name"`
	AuthorLastName     string                  `json:"author_last_name"`
}

// Example of a join to handle that prisma 'author' relation
func (q *Queries) GetCourseWithAuthor(ctx context.Context, id uuid.UUID) (GetCourseWithAuthorRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseWithAuthor, id)
	var i GetCourseWithAuthorRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CoverImageUri,
		&i.Status,
		&i.Category,
		&i.EstimatedDurations,
		&i.LearningOutcomes,
		&i.IsStrictSequencing,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorFirstName,
		&i.AuthorLastName,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    pes_number,
    password,
    first_name,
    last_name,
    email,
    role,
    cluster,
    title,
    gender,
    band,
    grade,
    ic,
    sbg,
    bu,
    segment,
    department,
    base_location,
    is_id,
    ns_id,
    dh_id
FROM users
WHERE email = ?
`

type GetUserByEmailRow struct {
	ID           uuid.UUID      `json:"id"`
	PesNumber    string         `json:"pes_number"`
	Password     string         `json:"password"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Role         models.Role    `json:"role"`
	Cluster      sql.NullString `json:"cluster"`
	Title        string         `json:"title"`
	Gender       string         `json:"gender"`
	Band         string         `json:"band"`
	Grade        string         `json:"grade"`
	Ic           string         `json:"ic"`
	Sbg          string         `json:"sbg"`
	Bu           string         `json:"bu"`
	Segment      string         `json:"segment"`
	Department   string         `json:"department"`
	BaseLocation string         `json:"base_location"`
	IsID         uuid.NullUUID  `json:"is_id"`
	NsID         uuid.NullUUID  `json:"ns_id"`
	DhID         uuid.NullUUID  `json:"dh_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    pes_number,
    password,
    first_name,
    last_name,
    email,
    role,
    cluster,
    title,
    gender,
    band,
    grade,
    ic,
    sbg,
    bu,
    segment,
    department,
    base_location,
    is_id,
    ns_id,
    dh_id
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID           uuid.UUID      `json:"id"`
	PesNumber    string         `json:"pes_number"`
	Password     string         `json:"password"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Role         models.Role    `json:"role"`
	Cluster      sql.NullString `json:"cluster"`
	Title        string         `json:"title"`
	Gender       string         `json:"gender"`
	Band         string         `json:"band"`
	Grade        string         `json:"grade"`
	Ic           string         `json:"ic"`
	Sbg          string         `json:"sbg"`
	Bu           string         `json:"bu"`
	Segment      string         `json:"segment"`
	Department   string         `json:"department"`
	BaseLocation string         `json:"base_location"`
	IsID         uuid.NullUUID  `json:"is_id"`
	NsID         uuid.NullUUID  `json:"ns_id"`
	DhID         uuid.NullUUID  `json:"dh_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const listActiveTrainings = `-- name: ListActiveTrainings :many
SELECT
    id,
    title,
    description,
    category,
    start_date,
    end_date,
    location,
    virtual_link,
    pre_read_uri,
    created_by_id,
    deadline_days,
    hr_program_id,
    mapped_category,
    mode_of_delivery,
    instructor_name,
    institute_partner_name,
    process_owner_name,
    process_owner_email,
    duration_manhours,
    training_mandays,
    facility_id,
    is_active
FROM trainings
WHERE is_active = 1
ORDER BY start_date ASC
`

type ListActiveTrainingsRow struct {
	ID                   uuid.UUID               `json:"id"`
	Title                string                  `json:"title"`
	Description          sql.NullString          `json:"description"`
	Category             models.TrainingCategory `json:"category"`
	StartDate            time.Time               `json:"start_date"`
	EndDate              time.Time               `json:"end_date"`
	Location             sql.NullString          `json:"location"`
	VirtualLink          sql.NullString          `json:"virtual_link"`
	PreReadUri           sql.NullString          `json:"pre_read_uri"`
	CreatedByID          uuid.UUID               `json:"created_by_id"`
	DeadlineDays         int64                   `json:"deadline_days"`
	HrProgramID          uuid.UUID               `json:"hr_program_id"`
	MappedCategory       string                  `json:"mapped_category"`
	ModeOfDelivery       models.DeliveryMode     `json:"mode_of_delivery"`
	InstructorName       string                  `json:"instructor_name"`
	InstitutePartnerName sql.NullString          `json:"institute_partner_name"`
	ProcessOwnerName     sql.NullString          `json:"process_owner_name"`
	ProcessOwnerEmail    sql.NullString          `json:"process_owner_email"`
	DurationManhours     sql.NullFloat64         `json:"duration_manhours"`
	TrainingMandays      sql.NullFloat64         `json:"training_mandays"`
	FacilityID           uuid.UUID               `json:"facility_id"`
	IsActive             bool                    `json:"is_active"`
}

func (q *Queries) ListActiveTrainings(ctx context.Context) ([]ListActiveTrainingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTrainings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTrainingsRow
	for rows.Next() {
		var i ListActiveTrainingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.VirtualLink,
			&i.PreReadUri,
			&i.CreatedByID,
			&i.DeadlineDays,
			&i.HrProgramID,
			&i.MappedCategory,
			&i.ModeOfDelivery,
			&i.InstructorName,
			&i.InstitutePartnerName,
			&i.ProcessOwnerName,
			&i.ProcessOwnerEmail,
			&i.DurationManhours,
			&i.TrainingMandays,
			&i.FacilityID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    pes_number,
    password,
    first_name,
    last_name,
    email,
    role,
    cluster,
    title,
    gender,
    band,
    grade,
    ic,
    sbg,
    bu,
    segment,
    department,
    base_location,
    is_id,
    ns_id,
    dh_id
FROM users
ORDER BY first_name, last_name
`

type ListUsersRow struct {
	ID           uuid.UUID      `json:"id"`
	PesNumber    string         `json:"pes_number"`
	Password     string         `json:"password"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Role         models.Role    `json:"role"`
	Cluster      sql.NullString `json:"cluster"`
	Title        string         `json:"title"`
	Gender       string         `json:"gender"`
	Band         string         `json:"band"`
	Grade        string         `json:"grade"`
	Ic           string         `json:"ic"`
	Sbg          string         `json:"sbg"`
	Bu           string         `json:"bu"`
	Segment      string         `json:"segment"`
	Department   string         `json:"department"`
	BaseLocation string         `json:"base_location"`
	IsID         uuid.NullUUID  `json:"is_id"`
	NsID         uuid.NullUUID  `json:"ns_id"`
	DhID         uuid.NullUUID  `json:"dh_id"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.PesNumber,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.Cluster,
			&i.Title,
			&i.Gender,
			&i.Band,
			&i.Grade,
			&i.Ic,
			&i.Sbg,
			&i.Bu,
			&i.Segment,
			&i.Department,
			&i.BaseLocation,
			&i.IsID,
			&i.NsID,
			&i.DhID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET is_active = ?
WHERE id = ?
`

type UpdateUserStatusParams struct {
	IsActive bool      `json:"is_active"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.IsActive, arg.ID)
	return err
}
