// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"go-server/internal/models"
)

const countNominationsByStatus = `-- name: CountNominationsByStatus :one
SELECT
    COUNT(*) AS total_count,
    SUM(CASE WHEN status = 'PENDING_MANAGER' THEN 1 ELSE 0 END)
        AS pending_count,
    SUM(CASE WHEN status = 'APPROVED' THEN 1 ELSE 0 END) AS approved_count,
    SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) AS completed_count,
    SUM(CASE WHEN status = 'ATTENDED' THEN 1 ELSE 0 END) AS attended_count
FROM nominations
`

type CountNominationsByStatusRow struct {
	TotalCount     int64           `json:"total_count"`
	PendingCount   sql.NullFloat64 `json:"pending_count"`
	ApprovedCount  sql.NullFloat64 `json:"approved_count"`
	CompletedCount sql.NullFloat64 `json:"completed_count"`
	AttendedCount  sql.NullFloat64 `json:"attended_count"`
}

func (q *Queries) CountNominationsByStatus(ctx context.Context) (CountNominationsByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countNominationsByStatus)
	var i CountNominationsByStatusRow
	err := row.Scan(
		&i.TotalCount,
		&i.PendingCount,
		&i.ApprovedCount,
		&i.CompletedCount,
		&i.AttendedCount,
	)
	return i, err
}

const countNominationsByUserID = `-- name: CountNominationsByUserID :one
SELECT
    COUNT(*) AS total_count,
    SUM(CASE WHEN status = 'PENDING_MANAGER' THEN 1 ELSE 0 END)
        AS pending_count,
    SUM(CASE WHEN status = 'APPROVED' THEN 1 ELSE 0 END) AS approved_count,
    SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) AS completed_count,
    SUM(CASE WHEN status = 'ATTENDED' THEN 1 ELSE 0 END) AS attended_count
FROM nominations
WHERE user_id = ?
`

type CountNominationsByUserIDRow struct {
	TotalCount     int64           `json:"total_count"`
	PendingCount   sql.NullFloat64 `json:"pending_count"`
	ApprovedCount  sql.NullFloat64 `json:"approved_count"`
	CompletedCount sql.NullFloat64 `json:"completed_count"`
	AttendedCount  sql.NullFloat64 `json:"attended_count"`
}

func (q *Queries) CountNominationsByUserID(ctx context.Context, userID uuid.UUID) (CountNominationsByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, countNominationsByUserID, userID)
	var i CountNominationsByUserIDRow
	err := row.Scan(
		&i.TotalCount,
		&i.PendingCount,
		&i.ApprovedCount,
		&i.CompletedCount,
		&i.AttendedCount,
	)
	return i, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) FROM users
WHERE is_id = ?
`

func (q *Queries) CountTeamMembers(ctx context.Context, isID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembers, isID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamNominationsByManager = `-- name: CountTeamNominationsByManager :one
SELECT
    COUNT(*) AS total_count,
    SUM(CASE WHEN status = 'PENDING_MANAGER' THEN 1 ELSE 0 END)
        AS pending_count,
    SUM(CASE WHEN status = 'APPROVED' THEN 1 ELSE 0 END) AS approved_count,
    SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) AS completed_count,
    SUM(CASE WHEN status = 'ATTENDED' THEN 1 ELSE 0 END) AS attended_count
FROM nominations n
JOIN users u ON n.user_id = u.id
WHERE u.is_id = ?
`

type CountTeamNominationsByManagerRow struct {
	TotalCount     int64           `json:"total_count"`
	PendingCount   sql.NullFloat64 `json:"pending_count"`
	ApprovedCount  sql.NullFloat64 `json:"approved_count"`
	CompletedCount sql.NullFloat64 `json:"completed_count"`
	AttendedCount  sql.NullFloat64 `json:"attended_count"`
}

func (q *Queries) CountTeamNominationsByManager(ctx context.Context, isID uuid.NullUUID) (CountTeamNominationsByManagerRow, error) {
	row := q.db.QueryRowContext(ctx, countTeamNominationsByManager, isID)
	var i CountTeamNominationsByManagerRow
	err := row.Scan(
		&i.TotalCount,
		&i.PendingCount,
		&i.ApprovedCount,
		&i.CompletedCount,
		&i.AttendedCount,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    id, title, description, author_id, cover_image_uri, status,
    category, estimated_durations, learning_outcomes, is_strict_sequencing,
    version, published_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, description, author_id, cover_image_uri, status, category, estimated_durations, learning_outcomes, is_strict_sequencing, version, published_at, created_at, updated_at
`

type CreateCourseParams struct {
	ID                 uuid.UUID               `json:"id"`
	Title              string                  `json:"title"`
	Description        sql.NullString          `json:"description"`
	AuthorID           uuid.NullUUID           `json:"author_id"`
	CoverImageUri      sql.NullString          `json:"cover_image_uri"`
	Status             models.CourseStatus     `json:"status"`
	Category           models.TrainingCategory `json:"category"`
	EstimatedDurations sql.NullInt64           `json:"estimated_durations"`
	LearningOutcomes   string                  `json:"learning_outcomes"`
	IsStrictSequencing bool                    `json:"is_strict_sequencing"`
	Version            int64                   `json:"version"`
	PublishedAt        sql.NullTime            `json:"published_at"`
}

// COURSE
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.CoverImageUri,
		arg.Status,
		arg.Category,
		arg.EstimatedDurations,
		arg.LearningOutcomes,
		arg.IsStrictSequencing,
		arg.Version,
		arg.PublishedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CoverImageUri,
		&i.Status,
		&i.Category,
		&i.EstimatedDurations,
		&i.LearningOutcomes,
		&i.IsStrictSequencing,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCourseAssignment = `-- name: CreateCourseAssignment :one
INSERT INTO course_assignments (
    id, status, progress_percentage, course_version, due_date,
    course_id, user_id, assigned_by_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, status, progress_percentage, course_version, due_date, enrolled_at, completed_at, course_id, user_id, assigned_by_id
`

type CreateCourseAssignmentParams struct {
	ID                 uuid.UUID                     `json:"id"`
	Status             models.CourseAssignmentStatus `json:"status"`
	ProgressPercentage float64                       `json:"progress_percentage"`
	CourseVersion      int64                         `json:"course_version"`
	DueDate            sql.NullTime                  `json:"due_date"`
	CourseID           uuid.UUID                     `json:"course_id"`
	UserID             uuid.NullUUID                 `json:"user_id"`
	AssignedByID       uuid.NullUUID                 `json:"assigned_by_id"`
}

// COURSE ASSIGNMENT
func (q *Queries) CreateCourseAssignment(ctx context.Context, arg CreateCourseAssignmentParams) (CourseAssignment, error) {
	row := q.db.QueryRowContext(ctx, createCourseAssignment,
		arg.ID,
		arg.Status,
		arg.ProgressPercentage,
		arg.CourseVersion,
		arg.DueDate,
		arg.CourseID,
		arg.UserID,
		arg.AssignedByID,
	)
	var i CourseAssignment
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ProgressPercentage,
		&i.CourseVersion,
		&i.DueDate,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.CourseID,
		&i.UserID,
		&i.AssignedByID,
	)
	return i, err
}

const createCourseModule = `-- name: CreateCourseModule :one
INSERT INTO course_modules (
    id, title, course_id, description, sequence_order
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, title, course_id, description, sequence_order, created_at, updated_at
`

type CreateCourseModuleParams struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	CourseID      uuid.UUID      `json:"course_id"`
	Description   sql.NullString `json:"description"`
	SequenceOrder int64          `json:"sequence_order"`
}

// COURSE MODULE
func (q *Queries) CreateCourseModule(ctx context.Context, arg CreateCourseModuleParams) (CourseModule, error) {
	row := q.db.QueryRowContext(ctx, createCourseModule,
		arg.ID,
		arg.Title,
		arg.CourseID,
		arg.Description,
		arg.SequenceOrder,
	)
	var i CourseModule
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CourseID,
		&i.Description,
		&i.SequenceOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (
    id, title, content_type, asset_uri, rich_text_content,
    duration_minutes, sequence_order, module_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, content_type, asset_uri, rich_text_content, duration_minutes, sequence_order, module_id, created_at, updated_at
`

type CreateLessonParams struct {
	ID              uuid.UUID                `json:"id"`
	Title           string                   `json:"title"`
	ContentType     models.LessonContentType `json:"content_type"`
	AssetUri        sql.NullString           `json:"asset_uri"`
	RichTextContent sql.NullString           `json:"rich_text_content"`
	DurationMinutes sql.NullInt64            `json:"duration_minutes"`
	SequenceOrder   int64                    `json:"sequence_order"`
	ModuleID        uuid.UUID                `json:"module_id"`
}

// LESSON
func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, createLesson,
		arg.ID,
		arg.Title,
		arg.ContentType,
		arg.AssetUri,
		arg.RichTextContent,
		arg.DurationMinutes,
		arg.SequenceOrder,
		arg.ModuleID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentType,
		&i.AssetUri,
		&i.RichTextContent,
		&i.DurationMinutes,
		&i.SequenceOrder,
		&i.ModuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNomination = `-- name: CreateNomination :one
INSERT INTO nominations (
    id, status, user_id, training_id, nominated_by_id,
    hr_completion_status, prof_fees, venue_cost, other_cost,
    non_tems_travel, non_tems_accommodation, total_cost
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
RETURNING id, status, user_id, training_id, nominated_by_id, hr_completion_status, prof_fees, venue_cost, other_cost, non_tems_travel, non_tems_accommodation, total_cost, created_at, updated_at
`

type CreateNominationParams struct {
	ID                   uuid.UUID               `json:"id"`
	Status               models.NominationStatus `json:"status"`
	UserID               uuid.UUID               `json:"user_id"`
	TrainingID           uuid.UUID               `json:"training_id"`
	NominatedByID        uuid.UUID               `json:"nominated_by_id"`
	HrCompletionStatus   sql.NullString          `json:"hr_completion_status"`
	ProfFees             sql.NullFloat64         `json:"prof_fees"`
	VenueCost            sql.NullFloat64         `json:"venue_cost"`
	OtherCost            sql.NullFloat64         `json:"other_cost"`
	NonTemsTravel        sql.NullFloat64         `json:"non_tems_travel"`
	NonTemsAccommodation sql.NullFloat64         `json:"non_tems_accommodation"`
	TotalCost            sql.NullFloat64         `json:"total_cost"`
}

// NOMINATIONS
func (q *Queries) CreateNomination(ctx context.Context, arg CreateNominationParams) (Nomination, error) {
	row := q.db.QueryRowContext(ctx, createNomination,
		arg.ID,
		arg.Status,
		arg.UserID,
		arg.TrainingID,
		arg.NominatedByID,
		arg.HrCompletionStatus,
		arg.ProfFees,
		arg.VenueCost,
		arg.OtherCost,
		arg.NonTemsTravel,
		arg.NonTemsAccommodation,
		arg.TotalCost,
	)
	var i Nomination
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserID,
		&i.TrainingID,
		&i.NominatedByID,
		&i.HrCompletionStatus,
		&i.ProfFees,
		&i.VenueCost,
		&i.OtherCost,
		&i.NonTemsTravel,
		&i.NonTemsAccommodation,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (
    id, title, description, category, start_date, end_date,
    location, virtual_link, pre_read_uri, created_by_id,
    deadline_days, hr_program_id, mapped_category, mode_of_delivery,
    instructor_name, institute_partner_name, process_owner_name,
    process_owner_email, duration_manhours, training_mandays,
    facility_id
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?
)
RETURNING id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at
`

type CreateTrainingParams struct {
	ID                   uuid.UUID               `json:"id"`
	Title                string                  `json:"title"`
	Description          sql.NullString          `json:"description"`
	Category             models.TrainingCategory `json:"category"`
	StartDate            time.Time               `json:"start_date"`
	EndDate              time.Time               `json:"end_date"`
	Location             sql.NullString          `json:"location"`
	VirtualLink          sql.NullString          `json:"virtual_link"`
	PreReadUri           sql.NullString          `json:"pre_read_uri"`
	CreatedByID          uuid.UUID               `json:"created_by_id"`
	DeadlineDays         int64                   `json:"deadline_days"`
	HrProgramID          uuid.UUID               `json:"hr_program_id"`
	MappedCategory       string                  `json:"mapped_category"`
	ModeOfDelivery       models.DeliveryMode     `json:"mode_of_delivery"`
	InstructorName       string                  `json:"instructor_name"`
	InstitutePartnerName sql.NullString          `json:"institute_partner_name"`
	ProcessOwnerName     sql.NullString          `json:"process_owner_name"`
	ProcessOwnerEmail    sql.NullString          `json:"process_owner_email"`
	DurationManhours     sql.NullFloat64         `json:"duration_manhours"`
	TrainingMandays      sql.NullFloat64         `json:"training_mandays"`
	FacilityID           uuid.UUID               `json:"facility_id"`
}

// TRAININGS
func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, createTraining,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.VirtualLink,
		arg.PreReadUri,
		arg.CreatedByID,
		arg.DeadlineDays,
		arg.HrProgramID,
		arg.MappedCategory,
		arg.ModeOfDelivery,
		arg.InstructorName,
		arg.InstitutePartnerName,
		arg.ProcessOwnerName,
		arg.ProcessOwnerEmail,
		arg.DurationManhours,
		arg.TrainingMandays,
		arg.FacilityID,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.VirtualLink,
		&i.PreReadUri,
		&i.CreatedByID,
		&i.DeadlineDays,
		&i.HrProgramID,
		&i.MappedCategory,
		&i.ModeOfDelivery,
		&i.InstructorName,
		&i.InstitutePartnerName,
		&i.ProcessOwnerName,
		&i.ProcessOwnerEmail,
		&i.DurationManhours,
		&i.TrainingMandays,
		&i.FacilityID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, pes_number, password, first_name, last_name,
    email, role, cluster, title, gender, band, grade,
    ic, sbg, bu, segment, department, base_location,
    is_id, ns_id, dh_id
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?
)
RETURNING id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
`

type CreateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	PesNumber    string         `json:"pes_number"`
	Password     string         `json:"password"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Role         models.Role    `json:"role"`
	Cluster      sql.NullString `json:"cluster"`
	Title        string         `json:"title"`
	Gender       string         `json:"gender"`
	Band         string         `json:"band"`
	Grade        string         `json:"grade"`
	Ic           string         `json:"ic"`
	Sbg          string         `json:"sbg"`
	Bu           string         `json:"bu"`
	Segment      string         `json:"segment"`
	Department   string         `json:"department"`
	BaseLocation string         `json:"base_location"`
	IsID         uuid.NullUUID  `json:"is_id"`
	NsID         uuid.NullUUID  `json:"ns_id"`
	DhID         uuid.NullUUID  `json:"dh_id"`
}

// USERS
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.PesNumber,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
		arg.Cluster,
		arg.Title,
		arg.Gender,
		arg.Band,
		arg.Grade,
		arg.Ic,
		arg.Sbg,
		arg.Bu,
		arg.Segment,
		arg.Department,
		arg.BaseLocation,
		arg.IsID,
		arg.NsID,
		arg.DhID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM trainings
WHERE id = ?
`

func (q *Queries) DeleteTraining(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTraining, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAdminKpis = `-- name: GetAdminKpis :one
WITH training_counts AS (
    SELECT COUNT(*) as total_trainings
    FROM trainings
    WHERE is_active = 1
),
nomination_stats AS (
    SELECT
        COUNT(*) FILTER (WHERE status IN ('APPROVED', 'COMPLETED', 'ATTENDED'))
            AS total_participants,
        COUNT(*) FILTER (WHERE status = 'COMPLETED') AS completed_count,
        COUNT(*) FILTER (WHERE status IN ('APPROVED', 'COMPLETED', 'ATTENDED'))
            AS enrolled_count
    FROM nominations
),
mandays_calc AS (
    SELECT
        COALESCE(SUM((julianday(t.end_date) - julianday(t.start_date) + 1)), 0.0)
            AS total_man_days
    FROM trainings t
    JOIN nominations n ON t.id = n.training_id
    WHERE t.is_active = 1 AND n.status IN ('APPROVED', 'COMPLETED', 'ATTENDED')
)
SELECT
    tc.total_trainings,
    ns.total_participants,
    ns.completed_count,
    ns.enrolled_count,
    mc.total_man_days
FROM training_counts tc, nomination_stats ns, mandays_calc mc
`

type GetAdminKpisRow struct {
	TotalTrainings    int64       `json:"total_trainings"`
	TotalParticipants int64       `json:"total_participants"`
	CompletedCount    int64       `json:"completed_count"`
	EnrolledCount     int64       `json:"enrolled_count"`
	TotalManDays      interface{} `json:"total_man_days"`
}

// ADMIN STATS
func (q *Queries) GetAdminKpis(ctx context.Context) (GetAdminKpisRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminKpis)
	var i GetAdminKpisRow
	err := row.Scan(
		&i.TotalTrainings,
		&i.TotalParticipants,
		&i.CompletedCount,
		&i.EnrolledCount,
		&i.TotalManDays,
	)
	return i, err
}

const getAllActiveAndUpcomingTrainings = `-- name: GetAllActiveAndUpcomingTrainings :many
SELECT id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at FROM trainings
WHERE start_date > CURRENT_TIMESTAMP OR is_active = 1
ORDER BY start_date ASC
`

func (q *Queries) GetAllActiveAndUpcomingTrainings(ctx context.Context) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveAndUpcomingTrainings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.VirtualLink,
			&i.PreReadUri,
			&i.CreatedByID,
			&i.DeadlineDays,
			&i.HrProgramID,
			&i.MappedCategory,
			&i.ModeOfDelivery,
			&i.InstructorName,
			&i.InstitutePartnerName,
			&i.ProcessOwnerName,
			&i.ProcessOwnerEmail,
			&i.DurationManhours,
			&i.TrainingMandays,
			&i.FacilityID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryDistribution = `-- name: GetCategoryDistribution :many
SELECT
    t.category AS name,
    COUNT(n.id) AS value
FROM nominations n
JOIN trainings t ON n.training_id = t.id
WHERE n.status IN ('APPROVED', 'COMPLETED', 'ATTENDED')
GROUP BY t.category
`

type GetCategoryDistributionRow struct {
	Name  models.TrainingCategory `json:"name"`
	Value int64                   `json:"value"`
}

func (q *Queries) GetCategoryDistribution(ctx context.Context) ([]GetCategoryDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryDistributionRow
	for rows.Next() {
		var i GetCategoryDistributionRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClusterStats = `-- name: GetClusterStats :many
SELECT
    COALESCE(u.cluster, 'Unassigned') AS cluster,
    COUNT(u.id) AS total_employees,
    COUNT(DISTINCT CASE WHEN n.id IS NOT NULL THEN u.id END) AS trained,
    (
        COUNT(u.id) - COUNT(DISTINCT CASE WHEN n.id IS NOT NULL THEN u.id END)
    ) AS untrained
FROM users u
LEFT JOIN
    nominations n
    ON
        u.id = n.user_id AND n.status IN ('APPROVED', 'COMPLETED', 'ATTENDED')
WHERE u.is_active = 1 AND u.role != 'ADMIN'
GROUP BY u.cluster
`

type GetClusterStatsRow struct {
	Cluster        string      `json:"cluster"`
	TotalEmployees int64       `json:"total_employees"`
	Trained        int64       `json:"trained"`
	Untrained      interface{} `json:"untrained"`
}

func (q *Queries) GetClusterStats(ctx context.Context) ([]GetClusterStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getClusterStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClusterStatsRow
	for rows.Next() {
		var i GetClusterStatsRow
		if err := rows.Scan(
			&i.Cluster,
			&i.TotalEmployees,
			&i.Trained,
			&i.Untrained,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseByTitle = `-- name: GetCourseByTitle :one
SELECT id, title, description, author_id, cover_image_uri, status, category, estimated_durations, learning_outcomes, is_strict_sequencing, version, published_at, created_at, updated_at FROM courses
WHERE title = ?
`

func (q *Queries) GetCourseByTitle(ctx context.Context, title string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByTitle, title)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CoverImageUri,
		&i.Status,
		&i.Category,
		&i.EstimatedDurations,
		&i.LearningOutcomes,
		&i.IsStrictSequencing,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseWithAuthor = `-- name: GetCourseWithAuthor :one
SELECT
    c.id, c.title, c.description, c.author_id, c.cover_image_uri, c.status, c.category, c.estimated_durations, c.learning_outcomes, c.is_strict_sequencing, c.version, c.published_at, c.created_at, c.updated_at,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name
FROM courses c
JOIN users u ON c.author_id = u.id
WHERE c.id = ?
LIMIT 1
`

type GetCourseWithAuthorRow struct {
	ID                 uuid.UUID               `json:"id"`
	Title              string                  `json:"title"`
	Description        sql.NullString          `json:"description"`
	AuthorID           uuid.NullUUID           `json:"author_id"`
	CoverImageUri      sql.NullString          `json:"cover_image_uri"`
	Status             models.CourseStatus     `json:"status"`
	Category           models.TrainingCategory `json:"category"`
	EstimatedDurations sql.NullInt64           `json:"estimated_durations"`
	LearningOutcomes   string                  `json:"learning_outcomes"`
	IsStrictSequencing bool                    `json:"is_strict_sequencing"`
	Version            int64                   `json:"version"`
	PublishedAt        sql.NullTime            `json:"published_at"`
	CreatedAt          time.Time               `json:"created_at"`
	UpdatedAt          time.Time               `json:"updated_at"`
	AuthorFirstName    string                  `json:"author_first_name"`
	AuthorLastName     string                  `json:"author_last_name"`
}

func (q *Queries) GetCourseWithAuthor(ctx context.Context, id uuid.UUID) (GetCourseWithAuthorRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseWithAuthor, id)
	var i GetCourseWithAuthorRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CoverImageUri,
		&i.Status,
		&i.Category,
		&i.EstimatedDurations,
		&i.LearningOutcomes,
		&i.IsStrictSequencing,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorFirstName,
		&i.AuthorLastName,
	)
	return i, err
}

const getMonthlyStats = `-- name: GetMonthlyStats :many
SELECT
    strftime('%Y-%m', t.start_date) AS month_key,
    strftime('%b %y', t.start_date) AS month_label,
    COUNT(n.id) AS participant_count,
    COUNT(DISTINCT t.id) AS training_count
FROM nominations n
JOIN trainings t ON n.training_id = t.id
WHERE n.status IN ('APPROVED', 'COMPLETED', 'ATTENDED')
GROUP BY month_key
ORDER BY month_key ASC
`

type GetMonthlyStatsRow struct {
	MonthKey         interface{} `json:"month_key"`
	MonthLabel       interface{} `json:"month_label"`
	ParticipantCount int64       `json:"participant_count"`
	TrainingCount    int64       `json:"training_count"`
}

func (q *Queries) GetMonthlyStats(ctx context.Context) ([]GetMonthlyStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyStatsRow
	for rows.Next() {
		var i GetMonthlyStatsRow
		if err := rows.Scan(
			&i.MonthKey,
			&i.MonthLabel,
			&i.ParticipantCount,
			&i.TrainingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNominationByID = `-- name: GetNominationByID :one
SELECT id, status, user_id, training_id, nominated_by_id, hr_completion_status, prof_fees, venue_cost, other_cost, non_tems_travel, non_tems_accommodation, total_cost, created_at, updated_at FROM nominations
WHERE id = ?
`

func (q *Queries) GetNominationByID(ctx context.Context, id uuid.UUID) (Nomination, error) {
	row := q.db.QueryRowContext(ctx, getNominationByID, id)
	var i Nomination
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserID,
		&i.TrainingID,
		&i.NominatedByID,
		&i.HrCompletionStatus,
		&i.ProfFees,
		&i.VenueCost,
		&i.OtherCost,
		&i.NonTemsTravel,
		&i.NonTemsAccommodation,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNominationsByManagerID = `-- name: GetNominationsByManagerID :many
SELECT n.id, n.status, n.user_id, n.training_id, n.nominated_by_id, n.hr_completion_status, n.prof_fees, n.venue_cost, n.other_cost, n.non_tems_travel, n.non_tems_accommodation, n.total_cost, n.created_at, n.updated_at FROM nominations n
JOIN users u ON n.user_id = u.id
WHERE u.is_id = ?
ORDER BY n.created_at DESC
`

func (q *Queries) GetNominationsByManagerID(ctx context.Context, isID uuid.NullUUID) ([]Nomination, error) {
	rows, err := q.db.QueryContext(ctx, getNominationsByManagerID, isID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nomination
	for rows.Next() {
		var i Nomination
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.UserID,
			&i.TrainingID,
			&i.NominatedByID,
			&i.HrCompletionStatus,
			&i.ProfFees,
			&i.VenueCost,
			&i.OtherCost,
			&i.NonTemsTravel,
			&i.NonTemsAccommodation,
			&i.TotalCost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNominationsByTrainingID = `-- name: GetNominationsByTrainingID :many
SELECT id, status, user_id, training_id, nominated_by_id, hr_completion_status, prof_fees, venue_cost, other_cost, non_tems_travel, non_tems_accommodation, total_cost, created_at, updated_at FROM nominations
WHERE training_id = ?
`

func (q *Queries) GetNominationsByTrainingID(ctx context.Context, trainingID uuid.UUID) ([]Nomination, error) {
	rows, err := q.db.QueryContext(ctx, getNominationsByTrainingID, trainingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nomination
	for rows.Next() {
		var i Nomination
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.UserID,
			&i.TrainingID,
			&i.NominatedByID,
			&i.HrCompletionStatus,
			&i.ProfFees,
			&i.VenueCost,
			&i.OtherCost,
			&i.NonTemsTravel,
			&i.NonTemsAccommodation,
			&i.TotalCost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNominationsByUserID = `-- name: GetNominationsByUserID :many
SELECT n.id, n.status, n.user_id, n.training_id, n.nominated_by_id, n.hr_completion_status, n.prof_fees, n.venue_cost, n.other_cost, n.non_tems_travel, n.non_tems_accommodation, n.total_cost, n.created_at, n.updated_at FROM nominations n
JOIN trainings t ON n.training_id = t.id
WHERE n.user_id = ?
ORDER BY t.start_date ASC
`

func (q *Queries) GetNominationsByUserID(ctx context.Context, userID uuid.UUID) ([]Nomination, error) {
	rows, err := q.db.QueryContext(ctx, getNominationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nomination
	for rows.Next() {
		var i Nomination
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.UserID,
			&i.TrainingID,
			&i.NominatedByID,
			&i.HrCompletionStatus,
			&i.ProfFees,
			&i.VenueCost,
			&i.OtherCost,
			&i.NonTemsTravel,
			&i.NonTemsAccommodation,
			&i.TotalCost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
FROM users
WHERE is_id = ?
`

func (q *Queries) GetTeamMembers(ctx context.Context, isID uuid.NullUUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembers, isID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PesNumber,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.Cluster,
			&i.Title,
			&i.Gender,
			&i.Band,
			&i.Grade,
			&i.Ic,
			&i.Sbg,
			&i.Bu,
			&i.Segment,
			&i.Department,
			&i.BaseLocation,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsID,
			&i.NsID,
			&i.DhID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainingByID = `-- name: GetTrainingByID :one
SELECT id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at FROM trainings
WHERE id = ?
`

func (q *Queries) GetTrainingByID(ctx context.Context, id uuid.UUID) (Training, error) {
	row := q.db.QueryRowContext(ctx, getTrainingByID, id)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.VirtualLink,
		&i.PreReadUri,
		&i.CreatedByID,
		&i.DeadlineDays,
		&i.HrProgramID,
		&i.MappedCategory,
		&i.ModeOfDelivery,
		&i.InstructorName,
		&i.InstitutePartnerName,
		&i.ProcessOwnerName,
		&i.ProcessOwnerEmail,
		&i.DurationManhours,
		&i.TrainingMandays,
		&i.FacilityID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingByTitle = `-- name: GetTrainingByTitle :one
SELECT id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at FROM trainings
WHERE title = ?
`

func (q *Queries) GetTrainingByTitle(ctx context.Context, title string) (Training, error) {
	row := q.db.QueryRowContext(ctx, getTrainingByTitle, title)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.VirtualLink,
		&i.PreReadUri,
		&i.CreatedByID,
		&i.DeadlineDays,
		&i.HrProgramID,
		&i.MappedCategory,
		&i.ModeOfDelivery,
		&i.InstructorName,
		&i.InstitutePartnerName,
		&i.ProcessOwnerName,
		&i.ProcessOwnerEmail,
		&i.DurationManhours,
		&i.TrainingMandays,
		&i.FacilityID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const getUserByPesNumber = `-- name: GetUserByPesNumber :one
SELECT id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
FROM users
WHERE pes_number = ?
`

func (q *Queries) GetUserByPesNumber(ctx context.Context, pesNumber string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPesNumber, pesNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const listActiveTrainings = `-- name: ListActiveTrainings :many
SELECT id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at FROM trainings
WHERE is_active = 1
ORDER BY start_date ASC
`

func (q *Queries) ListActiveTrainings(ctx context.Context) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTrainings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.VirtualLink,
			&i.PreReadUri,
			&i.CreatedByID,
			&i.DeadlineDays,
			&i.HrProgramID,
			&i.MappedCategory,
			&i.ModeOfDelivery,
			&i.InstructorName,
			&i.InstitutePartnerName,
			&i.ProcessOwnerName,
			&i.ProcessOwnerEmail,
			&i.DurationManhours,
			&i.TrainingMandays,
			&i.FacilityID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByCourse = `-- name: ListLessonsByCourse :many
SELECT l.id, l.title, l.content_type, l.asset_uri, l.rich_text_content, l.duration_minutes, l.sequence_order, l.module_id, l.created_at, l.updated_at FROM lessons l
JOIN course_modules m ON l.module_id = m.id
WHERE m.course_id = ?
ORDER BY m.sequence_order, l.sequence_order
`

func (q *Queries) ListLessonsByCourse(ctx context.Context, courseID uuid.UUID) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, listLessonsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContentType,
			&i.AssetUri,
			&i.RichTextContent,
			&i.DurationMinutes,
			&i.SequenceOrder,
			&i.ModuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNominationsByFilters = `-- name: ListNominationsByFilters :many
SELECT n.id, n.status, n.user_id, n.training_id, n.nominated_by_id, n.hr_completion_status, n.prof_fees, n.venue_cost, n.other_cost, n.non_tems_travel, n.non_tems_accommodation, n.total_cost, n.created_at, n.updated_at FROM nominations n
WHERE
    (COALESCE(?1, '') = '' OR n.status = ?1)
    AND (
        COALESCE(?2, '') = ''
        OR n.training_id = ?2
    )
    AND (
        COALESCE(?3, '') = ''
        OR n.user_id = ?3
    )
    AND (
        COALESCE(?4, '') = ''
        OR n.nominated_by_id = ?4
    )
ORDER BY n.created_at DESC
`

type ListNominationsByFiltersParams struct {
	Status        interface{} `json:"status"`
	TrainingID    interface{} `json:"training_id"`
	UserID        interface{} `json:"user_id"`
	NominatedByID interface{} `json:"nominated_by_id"`
}

func (q *Queries) ListNominationsByFilters(ctx context.Context, arg ListNominationsByFiltersParams) ([]Nomination, error) {
	rows, err := q.db.QueryContext(ctx, listNominationsByFilters,
		arg.Status,
		arg.TrainingID,
		arg.UserID,
		arg.NominatedByID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nomination
	for rows.Next() {
		var i Nomination
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.UserID,
			&i.TrainingID,
			&i.NominatedByID,
			&i.HrCompletionStatus,
			&i.ProfFees,
			&i.VenueCost,
			&i.OtherCost,
			&i.NonTemsTravel,
			&i.NonTemsAccommodation,
			&i.TotalCost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainings = `-- name: ListTrainings :many
SELECT id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at FROM trainings
ORDER BY start_date ASC
`

func (q *Queries) ListTrainings(ctx context.Context) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, listTrainings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.VirtualLink,
			&i.PreReadUri,
			&i.CreatedByID,
			&i.DeadlineDays,
			&i.HrProgramID,
			&i.MappedCategory,
			&i.ModeOfDelivery,
			&i.InstructorName,
			&i.InstitutePartnerName,
			&i.ProcessOwnerName,
			&i.ProcessOwnerEmail,
			&i.DurationManhours,
			&i.TrainingMandays,
			&i.FacilityID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingsByCategory = `-- name: ListTrainingsByCategory :many
SELECT id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at FROM trainings
WHERE category = ? AND is_active = 1
ORDER BY start_date ASC
`

func (q *Queries) ListTrainingsByCategory(ctx context.Context, category models.TrainingCategory) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.VirtualLink,
			&i.PreReadUri,
			&i.CreatedByID,
			&i.DeadlineDays,
			&i.HrProgramID,
			&i.MappedCategory,
			&i.ModeOfDelivery,
			&i.InstructorName,
			&i.InstitutePartnerName,
			&i.ProcessOwnerName,
			&i.ProcessOwnerEmail,
			&i.DurationManhours,
			&i.TrainingMandays,
			&i.FacilityID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingTrainings = `-- name: ListUpcomingTrainings :many
SELECT id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at FROM trainings
WHERE start_date > CURRENT_TIMESTAMP AND is_active = 1
ORDER BY start_date ASC
`

func (q *Queries) ListUpcomingTrainings(ctx context.Context) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingTrainings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.VirtualLink,
			&i.PreReadUri,
			&i.CreatedByID,
			&i.DeadlineDays,
			&i.HrProgramID,
			&i.MappedCategory,
			&i.ModeOfDelivery,
			&i.InstructorName,
			&i.InstitutePartnerName,
			&i.ProcessOwnerName,
			&i.ProcessOwnerEmail,
			&i.DurationManhours,
			&i.TrainingMandays,
			&i.FacilityID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
FROM users
ORDER BY first_name, last_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PesNumber,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.Cluster,
			&i.Title,
			&i.Gender,
			&i.Band,
			&i.Grade,
			&i.Ic,
			&i.Sbg,
			&i.Bu,
			&i.Segment,
			&i.Department,
			&i.BaseLocation,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsID,
			&i.NsID,
			&i.DhID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNominationStatus = `-- name: UpdateNominationStatus :one
UPDATE nominations SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, status, user_id, training_id, nominated_by_id, hr_completion_status, prof_fees, venue_cost, other_cost, non_tems_travel, non_tems_accommodation, total_cost, created_at, updated_at
`

type UpdateNominationStatusParams struct {
	Status models.NominationStatus `json:"status"`
	ID     uuid.UUID               `json:"id"`
}

func (q *Queries) UpdateNominationStatus(ctx context.Context, arg UpdateNominationStatusParams) (Nomination, error) {
	row := q.db.QueryRowContext(ctx, updateNominationStatus, arg.Status, arg.ID)
	var i Nomination
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserID,
		&i.TrainingID,
		&i.NominatedByID,
		&i.HrCompletionStatus,
		&i.ProfFees,
		&i.VenueCost,
		&i.OtherCost,
		&i.NonTemsTravel,
		&i.NonTemsAccommodation,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTraining = `-- name: UpdateTraining :one
UPDATE trainings SET
    title = COALESCE(?1, title),
    description = COALESCE(?2, description),
    category = COALESCE(NULLIF(?3, ''), category),
    start_date = COALESCE(?4, start_date),
    end_date = COALESCE(?5, end_date),
    location = COALESCE(?6, location),
    virtual_link = COALESCE(?7, virtual_link),
    pre_read_uri = COALESCE(?8, pre_read_uri),
    deadline_days = COALESCE(?9, deadline_days),
    mapped_category = COALESCE(?10, mapped_category),
    mode_of_delivery
    = COALESCE(NULLIF(?11, ''), mode_of_delivery),
    instructor_name = COALESCE(?12, instructor_name),
    institute_partner_name
    = COALESCE(?13, institute_partner_name),
    process_owner_name
    = COALESCE(?14, process_owner_name),
    process_owner_email
    = COALESCE(?15, process_owner_email),
    duration_manhours
    = COALESCE(?16, duration_manhours),
    training_mandays
    = COALESCE(?17, training_mandays),
    is_active = COALESCE(?18, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?19
RETURNING id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at
`

type UpdateTrainingParams struct {
	Title                sql.NullString  `json:"title"`
	Description          sql.NullString  `json:"description"`
	Category             interface{}     `json:"category"`
	StartDate            sql.NullTime    `json:"start_date"`
	EndDate              sql.NullTime    `json:"end_date"`
	Location             sql.NullString  `json:"location"`
	VirtualLink          sql.NullString  `json:"virtual_link"`
	PreReadUri           sql.NullString  `json:"pre_read_uri"`
	DeadlineDays         sql.NullInt64   `json:"deadline_days"`
	MappedCategory       sql.NullString  `json:"mapped_category"`
	ModeOfDelivery       interface{}     `json:"mode_of_delivery"`
	InstructorName       sql.NullString  `json:"instructor_name"`
	InstitutePartnerName sql.NullString  `json:"institute_partner_name"`
	ProcessOwnerName     sql.NullString  `json:"process_owner_name"`
	ProcessOwnerEmail    sql.NullString  `json:"process_owner_email"`
	DurationManhours     sql.NullFloat64 `json:"duration_manhours"`
	TrainingMandays      sql.NullFloat64 `json:"training_mandays"`
	IsActive             sql.NullBool    `json:"is_active"`
	ID                   uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateTraining(ctx context.Context, arg UpdateTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, updateTraining,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.VirtualLink,
		arg.PreReadUri,
		arg.DeadlineDays,
		arg.MappedCategory,
		arg.ModeOfDelivery,
		arg.InstructorName,
		arg.InstitutePartnerName,
		arg.ProcessOwnerName,
		arg.ProcessOwnerEmail,
		arg.DurationManhours,
		arg.TrainingMandays,
		arg.IsActive,
		arg.ID,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.VirtualLink,
		&i.PreReadUri,
		&i.CreatedByID,
		&i.DeadlineDays,
		&i.HrProgramID,
		&i.MappedCategory,
		&i.ModeOfDelivery,
		&i.InstructorName,
		&i.InstitutePartnerName,
		&i.ProcessOwnerName,
		&i.ProcessOwnerEmail,
		&i.DurationManhours,
		&i.TrainingMandays,
		&i.FacilityID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    first_name = COALESCE(?2, first_name),
    last_name = COALESCE(?3, last_name),
    title = COALESCE(?4, title),
    department = COALESCE(?5, department),
    base_location = COALESCE(?6, base_location)
WHERE id = ?
RETURNING id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
`

type UpdateUserParams struct {
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	Title        sql.NullString `json:"title"`
	Department   sql.NullString `json:"department"`
	BaseLocation sql.NullString `json:"base_location"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Title,
		arg.Department,
		arg.BaseLocation,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET is_active = ?
WHERE id = ?
`

type UpdateUserStatusParams struct {
	IsActive bool      `json:"is_active"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.IsActive, arg.ID)
	return err
}

const upsertCourse = `-- name: UpsertCourse :one
INSERT INTO courses (
    id, title, description, author_id, cover_image_uri, status,
    category, estimated_durations, learning_outcomes, is_strict_sequencing,
    version, published_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (title) DO UPDATE SET
    description = excluded.description,
    author_id = excluded.author_id,
    status = excluded.status,
    category = excluded.category,
    estimated_durations = excluded.estimated_durations,
    learning_outcomes = excluded.learning_outcomes,
    is_strict_sequencing = excluded.is_strict_sequencing,
    version = excluded.version,
    published_at = excluded.published_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, title, description, author_id, cover_image_uri, status, category, estimated_durations, learning_outcomes, is_strict_sequencing, version, published_at, created_at, updated_at
`

type UpsertCourseParams struct {
	ID                 uuid.UUID               `json:"id"`
	Title              string                  `json:"title"`
	Description        sql.NullString          `json:"description"`
	AuthorID           uuid.NullUUID           `json:"author_id"`
	CoverImageUri      sql.NullString          `json:"cover_image_uri"`
	Status             models.CourseStatus     `json:"status"`
	Category           models.TrainingCategory `json:"category"`
	EstimatedDurations sql.NullInt64           `json:"estimated_durations"`
	LearningOutcomes   string                  `json:"learning_outcomes"`
	IsStrictSequencing bool                    `json:"is_strict_sequencing"`
	Version            int64                   `json:"version"`
	PublishedAt        sql.NullTime            `json:"published_at"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, upsertCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.CoverImageUri,
		arg.Status,
		arg.Category,
		arg.EstimatedDurations,
		arg.LearningOutcomes,
		arg.IsStrictSequencing,
		arg.Version,
		arg.PublishedAt,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CoverImageUri,
		&i.Status,
		&i.Category,
		&i.EstimatedDurations,
		&i.LearningOutcomes,
		&i.IsStrictSequencing,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCourseAssignment = `-- name: UpsertCourseAssignment :one
INSERT INTO course_assignments (
    id, status, progress_percentage, course_version, due_date,
    course_id, user_id, assigned_by_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (user_id, course_id) DO UPDATE SET
    status = excluded.status,
    progress_percentage = excluded.progress_percentage,
    course_version = excluded.course_version,
    due_date = excluded.due_date,
    assigned_by_id = excluded.assigned_by_id
RETURNING id, status, progress_percentage, course_version, due_date, enrolled_at, completed_at, course_id, user_id, assigned_by_id
`

type UpsertCourseAssignmentParams struct {
	ID                 uuid.UUID                     `json:"id"`
	Status             models.CourseAssignmentStatus `json:"status"`
	ProgressPercentage float64                       `json:"progress_percentage"`
	CourseVersion      int64                         `json:"course_version"`
	DueDate            sql.NullTime                  `json:"due_date"`
	CourseID           uuid.UUID                     `json:"course_id"`
	UserID             uuid.NullUUID                 `json:"user_id"`
	AssignedByID       uuid.NullUUID                 `json:"assigned_by_id"`
}

func (q *Queries) UpsertCourseAssignment(ctx context.Context, arg UpsertCourseAssignmentParams) (CourseAssignment, error) {
	row := q.db.QueryRowContext(ctx, upsertCourseAssignment,
		arg.ID,
		arg.Status,
		arg.ProgressPercentage,
		arg.CourseVersion,
		arg.DueDate,
		arg.CourseID,
		arg.UserID,
		arg.AssignedByID,
	)
	var i CourseAssignment
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ProgressPercentage,
		&i.CourseVersion,
		&i.DueDate,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.CourseID,
		&i.UserID,
		&i.AssignedByID,
	)
	return i, err
}

const upsertCourseModule = `-- name: UpsertCourseModule :one
INSERT INTO course_modules (
    id, title, course_id, description, sequence_order
) VALUES (
    ?, ?, ?, ?, ?
)
ON CONFLICT (course_id, title) DO UPDATE SET
    description = excluded.description,
    sequence_order = excluded.sequence_order,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, title, course_id, description, sequence_order, created_at, updated_at
`

type UpsertCourseModuleParams struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	CourseID      uuid.UUID      `json:"course_id"`
	Description   sql.NullString `json:"description"`
	SequenceOrder int64          `json:"sequence_order"`
}

func (q *Queries) UpsertCourseModule(ctx context.Context, arg UpsertCourseModuleParams) (CourseModule, error) {
	row := q.db.QueryRowContext(ctx, upsertCourseModule,
		arg.ID,
		arg.Title,
		arg.CourseID,
		arg.Description,
		arg.SequenceOrder,
	)
	var i CourseModule
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CourseID,
		&i.Description,
		&i.SequenceOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLesson = `-- name: UpsertLesson :one
INSERT INTO lessons (
    id, title, content_type, asset_uri, rich_text_content,
    duration_minutes, sequence_order, module_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (module_id, title) DO UPDATE SET
    content_type = excluded.content_type,
    asset_uri = excluded.asset_uri,
    rich_text_content = excluded.rich_text_content,
    duration_minutes = excluded.duration_minutes,
    sequence_order = excluded.sequence_order,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, title, content_type, asset_uri, rich_text_content, duration_minutes, sequence_order, module_id, created_at, updated_at
`

type UpsertLessonParams struct {
	ID              uuid.UUID                `json:"id"`
	Title           string                   `json:"title"`
	ContentType     models.LessonContentType `json:"content_type"`
	AssetUri        sql.NullString           `json:"asset_uri"`
	RichTextContent sql.NullString           `json:"rich_text_content"`
	DurationMinutes sql.NullInt64            `json:"duration_minutes"`
	SequenceOrder   int64                    `json:"sequence_order"`
	ModuleID        uuid.UUID                `json:"module_id"`
}

func (q *Queries) UpsertLesson(ctx context.Context, arg UpsertLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, upsertLesson,
		arg.ID,
		arg.Title,
		arg.ContentType,
		arg.AssetUri,
		arg.RichTextContent,
		arg.DurationMinutes,
		arg.SequenceOrder,
		arg.ModuleID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentType,
		&i.AssetUri,
		&i.RichTextContent,
		&i.DurationMinutes,
		&i.SequenceOrder,
		&i.ModuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO lesson_progress (
    id, is_completed, last_playback_position, completed_at,
    assignment_id, lesson_id
) VALUES (
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT (assignment_id, lesson_id) DO UPDATE SET
    is_completed = excluded.is_completed,
    completed_at = excluded.completed_at,
    last_playback_position = excluded.last_playback_position
RETURNING id, is_completed, last_playback_position, completed_at, assignment_id, lesson_id
`

type UpsertLessonProgressParams struct {
	ID                   uuid.UUID    `json:"id"`
	IsCompleted          bool         `json:"is_completed"`
	LastPlaybackPosition int64        `json:"last_playback_position"`
	CompletedAt          sql.NullTime `json:"completed_at"`
	AssignmentID         uuid.UUID    `json:"assignment_id"`
	LessonID             uuid.UUID    `json:"lesson_id"`
}

// LESSON PROGRESS
func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertLessonProgress,
		arg.ID,
		arg.IsCompleted,
		arg.LastPlaybackPosition,
		arg.CompletedAt,
		arg.AssignmentID,
		arg.LessonID,
	)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.IsCompleted,
		&i.LastPlaybackPosition,
		&i.CompletedAt,
		&i.AssignmentID,
		&i.LessonID,
	)
	return i, err
}

const upsertNomination = `-- name: UpsertNomination :one
INSERT INTO nominations (
    id, status, user_id, training_id, nominated_by_id,
    hr_completion_status, prof_fees, venue_cost, other_cost,
    non_tems_travel, non_tems_accommodation, total_cost
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
ON CONFLICT (user_id, training_id) DO UPDATE SET
    status = excluded.status,
    nominated_by_id = excluded.nominated_by_id,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, status, user_id, training_id, nominated_by_id, hr_completion_status, prof_fees, venue_cost, other_cost, non_tems_travel, non_tems_accommodation, total_cost, created_at, updated_at
`

type UpsertNominationParams struct {
	ID                   uuid.UUID               `json:"id"`
	Status               models.NominationStatus `json:"status"`
	UserID               uuid.UUID               `json:"user_id"`
	TrainingID           uuid.UUID               `json:"training_id"`
	NominatedByID        uuid.UUID               `json:"nominated_by_id"`
	HrCompletionStatus   sql.NullString          `json:"hr_completion_status"`
	ProfFees             sql.NullFloat64         `json:"prof_fees"`
	VenueCost            sql.NullFloat64         `json:"venue_cost"`
	OtherCost            sql.NullFloat64         `json:"other_cost"`
	NonTemsTravel        sql.NullFloat64         `json:"non_tems_travel"`
	NonTemsAccommodation sql.NullFloat64         `json:"non_tems_accommodation"`
	TotalCost            sql.NullFloat64         `json:"total_cost"`
}

func (q *Queries) UpsertNomination(ctx context.Context, arg UpsertNominationParams) (Nomination, error) {
	row := q.db.QueryRowContext(ctx, upsertNomination,
		arg.ID,
		arg.Status,
		arg.UserID,
		arg.TrainingID,
		arg.NominatedByID,
		arg.HrCompletionStatus,
		arg.ProfFees,
		arg.VenueCost,
		arg.OtherCost,
		arg.NonTemsTravel,
		arg.NonTemsAccommodation,
		arg.TotalCost,
	)
	var i Nomination
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UserID,
		&i.TrainingID,
		&i.NominatedByID,
		&i.HrCompletionStatus,
		&i.ProfFees,
		&i.VenueCost,
		&i.OtherCost,
		&i.NonTemsTravel,
		&i.NonTemsAccommodation,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTraining = `-- name: UpsertTraining :one
INSERT INTO trainings (
    id, title, description, category, start_date, end_date,
    location, virtual_link, pre_read_uri, created_by_id,
    deadline_days, hr_program_id, mapped_category, mode_of_delivery,
    instructor_name, institute_partner_name, process_owner_name,
    process_owner_email, duration_manhours, training_mandays,
    facility_id
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?
)
ON CONFLICT (title) DO UPDATE SET
    description = excluded.description,
    category = excluded.category,
    start_date = excluded.start_date,
    end_date = excluded.end_date,
    location = excluded.location,
    virtual_link = excluded.virtual_link,
    pre_read_uri = excluded.pre_read_uri,
    deadline_days = excluded.deadline_days,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, title, description, category, start_date, end_date, location, virtual_link, pre_read_uri, created_by_id, deadline_days, hr_program_id, mapped_category, mode_of_delivery, instructor_name, institute_partner_name, process_owner_name, process_owner_email, duration_manhours, training_mandays, facility_id, is_active, created_at, updated_at
`

type UpsertTrainingParams struct {
	ID                   uuid.UUID               `json:"id"`
	Title                string                  `json:"title"`
	Description          sql.NullString          `json:"description"`
	Category             models.TrainingCategory `json:"category"`
	StartDate            time.Time               `json:"start_date"`
	EndDate              time.Time               `json:"end_date"`
	Location             sql.NullString          `json:"location"`
	VirtualLink          sql.NullString          `json:"virtual_link"`
	PreReadUri           sql.NullString          `json:"pre_read_uri"`
	CreatedByID          uuid.UUID               `json:"created_by_id"`
	DeadlineDays         int64                   `json:"deadline_days"`
	HrProgramID          uuid.UUID               `json:"hr_program_id"`
	MappedCategory       string                  `json:"mapped_category"`
	ModeOfDelivery       models.DeliveryMode     `json:"mode_of_delivery"`
	InstructorName       string                  `json:"instructor_name"`
	InstitutePartnerName sql.NullString          `json:"institute_partner_name"`
	ProcessOwnerName     sql.NullString          `json:"process_owner_name"`
	ProcessOwnerEmail    sql.NullString          `json:"process_owner_email"`
	DurationManhours     sql.NullFloat64         `json:"duration_manhours"`
	TrainingMandays      sql.NullFloat64         `json:"training_mandays"`
	FacilityID           uuid.UUID               `json:"facility_id"`
}

func (q *Queries) UpsertTraining(ctx context.Context, arg UpsertTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, upsertTraining,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.VirtualLink,
		arg.PreReadUri,
		arg.CreatedByID,
		arg.DeadlineDays,
		arg.HrProgramID,
		arg.MappedCategory,
		arg.ModeOfDelivery,
		arg.InstructorName,
		arg.InstitutePartnerName,
		arg.ProcessOwnerName,
		arg.ProcessOwnerEmail,
		arg.DurationManhours,
		arg.TrainingMandays,
		arg.FacilityID,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.VirtualLink,
		&i.PreReadUri,
		&i.CreatedByID,
		&i.DeadlineDays,
		&i.HrProgramID,
		&i.MappedCategory,
		&i.ModeOfDelivery,
		&i.InstructorName,
		&i.InstitutePartnerName,
		&i.ProcessOwnerName,
		&i.ProcessOwnerEmail,
		&i.DurationManhours,
		&i.TrainingMandays,
		&i.FacilityID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    id, pes_number, password, first_name, last_name,
    email, role, cluster, title, gender, band, grade,
    ic, sbg, bu, segment, department, base_location,
    is_id, ns_id, dh_id
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?
)
ON CONFLICT (pes_number) DO UPDATE SET
    password = excluded.password,
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    email = excluded.email,
    role = excluded.role,
    cluster = excluded.cluster,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, pes_number, password, first_name, last_name, email, role, cluster, title, gender, band, grade, ic, sbg, bu, segment, department, base_location, is_active, created_at, updated_at, is_id, ns_id, dh_id
`

type UpsertUserParams struct {
	ID           uuid.UUID      `json:"id"`
	PesNumber    string         `json:"pes_number"`
	Password     string         `json:"password"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Role         models.Role    `json:"role"`
	Cluster      sql.NullString `json:"cluster"`
	Title        string         `json:"title"`
	Gender       string         `json:"gender"`
	Band         string         `json:"band"`
	Grade        string         `json:"grade"`
	Ic           string         `json:"ic"`
	Sbg          string         `json:"sbg"`
	Bu           string         `json:"bu"`
	Segment      string         `json:"segment"`
	Department   string         `json:"department"`
	BaseLocation string         `json:"base_location"`
	IsID         uuid.NullUUID  `json:"is_id"`
	NsID         uuid.NullUUID  `json:"ns_id"`
	DhID         uuid.NullUUID  `json:"dh_id"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.ID,
		arg.PesNumber,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
		arg.Cluster,
		arg.Title,
		arg.Gender,
		arg.Band,
		arg.Grade,
		arg.Ic,
		arg.Sbg,
		arg.Bu,
		arg.Segment,
		arg.Department,
		arg.BaseLocation,
		arg.IsID,
		arg.NsID,
		arg.DhID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PesNumber,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Cluster,
		&i.Title,
		&i.Gender,
		&i.Band,
		&i.Grade,
		&i.Ic,
		&i.Sbg,
		&i.Bu,
		&i.Segment,
		&i.Department,
		&i.BaseLocation,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsID,
		&i.NsID,
		&i.DhID,
	)
	return i, err
}
